language: c++
os: linux
sudo: false

# This only exists because of a bug: https://github.com/travis-ci/travis-ci/issues/4681
env:
  matrix:
    - EMPTY_JOB_IN_TRAVIS_CI=1

addons:
  apt:
    packages: &default_dep
      - clang-3.6
      - libclang-3.6-dev
      - llvm-3.6
      - llvm-3.6-dev
      - zlib1g-dev
      - libxml2-dev
      - libedit-dev
    sources: &sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise

matrix:
  exclude:
    - env: EMPTY_JOB_IN_TRAVIS_CI=1
  include:
    - env: CLANG_VERSION=3.6 BUILD_TYPE=Release UNIT_TEST=1
    - env: CLANG_VERSION=3.8 BUILD_TYPE=Release UNIT_TEST=1
      addons: &clang38
        apt:
          packages:
            - *default_dep
            - clang-3.8
          sources: *sources

before_install:
  - export DEPENDENCY_DIR="${TRAVIS_BUILD_DIR}/dependency" 
  - mkdir -p ${DEPENDENCY_DIR}
  - cd ${DEPENDENCY_DIR}

install:
  - |
    CMAKE_URL="https://cmake.org/files/v3.6/cmake-3.6.3-Linux-x86_64.tar.gz"
    mkdir -p cmake
    travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
    export PATH=${DEPENDENCY_DIR}/cmake/bin:${PATH}
  - cmake --version

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - |
    if [[ -n $GCC_VERSION ]] ; then 
      export CXX="g++-${GCC_VERSION}"
      export CC="gcc-${GCC_VERSION}"
    fi
  - |
    if [[ -n $CLANG_VERSION ]] ; then 
      export CXX="clang++-${CLANG_VERSION}"
      export CC="clang-${CLANG_VERSION}"
    fi
  - export BUILD_DIR="build_${CC}_${SANITIZE}"
  - export BIN_DIR="bin_${CC}_${SANITIZE}"
  - mkdir -p ${BUILD_DIR}
  - cd ${BUILD_DIR}

script: 
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DBINARY_OUTPUT_DIRECTORY=${BIN_DIR} ..
  - cmake --build .
  - |
    if [[ $UNIT_TEST == 1 ]] ; then 
      ctest
    fi

branches:
  only:
    - master
